INSERT INTO properties (id, type, title, location, city, rent, deposit, sqft, bedrooms, bathrooms, furnishing, images, amenities, nearby_places, fomo_text, available)
VALUES
(
    'fam-001',
    'families',
    'Prestige Monte Carlo',
    'Yelahanka',
    'Bengaluru',
    45000,
    200000,
    1800,
    3,
    3,
    'Semi-Furnished',
    ARRAY['/images/placeholder-family-1.jpg','/images/placeholder-family-2.jpg','/images/placeholder-family-3.jpg'],
    ARRAY['Kid''s Play Area','Swimming Pool','24/7 Security','Power Backup','Park'],
    '[{"name":"Canadian International School","distance":"2 km"},{"name":"RMZ Galleria Mall","distance":"3 km"},{"name":"Aster CMI Hospital","distance":"5 km"}]'::jsonb,
    'Exclusively listed — Not available anywhere else',
    true
  ),
(
    'fam-002',
    'families',
    'Godrej Platinum',
    'Hebbal',
    'Bengaluru',
    65000,
    300000,
    2100,
    3,
    3,
    'Fully-Furnished',
    ARRAY['/images/placeholder-family-4.jpg','/images/placeholder-family-5.jpg','/images/placeholder-family-6.jpg'],
    ARRAY['Clubhouse','Gym','Badminton Court','Supermarket','Power Backup'],
    '[{"name":"Hebbal Lake","distance":"1 km"},{"name":"Manyata Tech Park","distance":"4 km"},{"name":"Baptist Hospital","distance":"2 km"}]'::jsonb,
    'Exclusively listed — Not available anywhere else',
    true
  ),
(
    'fam-003',
    'families',
    'L&T Raintree Boulevard',
    'Hebbal',
    'Bengaluru',
    55000,
    250000,
    1900,
    3,
    3,
    'Semi-Furnished',
    ARRAY['/images/placeholder-family-7.jpg','/images/placeholder-family-8.jpg','/images/placeholder-family-9.jpg'],
    ARRAY['Jogging Track','Tennis Court','Mini Theatre','Gym','Pool'],
    '[{"name":"Esteem Mall","distance":"1.5 km"},{"name":"Vidyashilp Academy","distance":"3 km"},{"name":"Airport Road","distance":"500 m"}]'::jsonb,
    'Exclusively listed — Not available anywhere else',
    true
  ),
(
    'fam-004',
    'families',
    'Purva Venezia',
    'Yelahanka',
    'Bengaluru',
    48000,
    220000,
    1650,
    2,
    2,
    'Fully-Furnished',
    ARRAY['/images/placeholder-family-10.jpg','/images/placeholder-family-1.jpg','/images/placeholder-family-2.jpg'],
    ARRAY['Open Greens','Indoor Games','Creche','Security','Grocery Store'],
    '[{"name":"Yelahanka New Town","distance":"1 km"},{"name":"Motherhood Hospital","distance":"2 km"},{"name":"Bhartiya City","distance":"5 km"}]'::jsonb,
    'Exclusively listed — Not available anywhere else',
    true
  ),
(
    'fam-005',
    'families',
    'Sobha City',
    'Hebbal',
    'Bengaluru',
    60000,
    280000,
    2000,
    3,
    3,
    'Semi-Furnished',
    ARRAY['/images/placeholder-family-3.jpg','/images/placeholder-family-4.jpg','/images/placeholder-family-5.jpg'],
    ARRAY['Luxury Pool','Spa','Cricket Pitch','Gym','Pet Park'],
    '[{"name":"Manyata Business Park","distance":"4 km"},{"name":"Jakkur Aerodrome","distance":"2 km"},{"name":"Elements Mall","distance":"3 km"}]'::jsonb,
    'Exclusively listed — Not available anywhere else',
    true
  ),
(
    'pro-001',
    'professionals',
    'Century Corvus',
    'Hebbal',
    'Bengaluru',
    30000,
    100000,
    900,
    1,
    1,
    'Fully-Furnished',
    ARRAY['/images/placeholder-pro-1.jpg','/images/placeholder-pro-2.jpg','/images/placeholder-pro-3.jpg'],
    ARRAY['WiFi Included','Gym','Laundromat','CCTV','Lounge Area'],
    '[{"name":"Manyata Tech Park","distance":"3 km"},{"name":"Hebbal Flyover","distance":"1.5 km"},{"name":"Cafe Coffee Day","distance":"500 m"}]'::jsonb,
    'Exclusively listed — Not available anywhere else',
    true
  ),
(
    'pro-002',
    'professionals',
    'Brigade Senator',
    'Hebbal',
    'Bengaluru',
    42000,
    150000,
    1200,
    2,
    2,
    'Fully-Furnished',
    ARRAY['/images/placeholder-pro-4.jpg','/images/placeholder-pro-5.jpg','/images/placeholder-pro-6.jpg'],
    ARRAY['Co-working Space','Pool','Power Backup','Gym','Parking'],
    '[{"name":"Kirloskar Tech Park","distance":"1 km"},{"name":"Aster CMI","distance":"1.5 km"},{"name":"Esteem Mall","distance":"2 km"}]'::jsonb,
    'Exclusively listed — Not available anywhere else',
    true
  ),
(
    'pro-003',
    'professionals',
    'NCC Urban',
    'Yelahanka',
    'Bengaluru',
    35000,
    120000,
    1100,
    2,
    2,
    'Semi-Furnished',
    ARRAY['/images/placeholder-pro-7.jpg','/images/placeholder-pro-8.jpg','/images/placeholder-pro-9.jpg'],
    ARRAY['Gym','Jogging Track','24/7 Security','Marketplace','Power Backup'],
    '[{"name":"Airport Road","distance":"1 km"},{"name":"RMZ Galleria Mall","distance":"3 km"},{"name":"Cytecare Hospital","distance":"4 km"}]'::jsonb,
    'Exclusively listed — Not available anywhere else',
    true
  ),
(
    'pro-004',
    'professionals',
    'RMZ Galleria Residences',
    'Yelahanka',
    'Bengaluru',
    50000,
    200000,
    1400,
    2,
    2,
    'Fully-Furnished',
    ARRAY['/images/placeholder-pro-10.jpg','/images/placeholder-pro-1.jpg','/images/placeholder-pro-2.jpg'],
    ARRAY['Direct Mall Access','Rooftop Pool','High-Tech Gym','Concierge','Lounge'],
    '[{"name":"Yelahanka Train Station","distance":"1 km"},{"name":"Bhartiya Centre of Tech","distance":"6 km"},{"name":"Airport","distance":"18 km"}]'::jsonb,
    'Exclusively listed — Not available anywhere else',
    true
  ),
(
    'pro-005',
    'professionals',
    'Zenith Residences',
    'Hebbal',
    'Bengaluru',
    45000,
    180000,
    1350,
    2,
    2,
    'Fully-Furnished',
    ARRAY['/images/placeholder-pro-3.jpg','/images/placeholder-pro-4.jpg','/images/placeholder-pro-5.jpg'],
    ARRAY['Smart Home','Infinity Pool','Clubhouse','Billiards','Valet'],
    '[{"name":"Karle Town Centre","distance":"1 km"},{"name":"Manyata Tech Park","distance":"2 km"},{"name":"Lakeview Park","distance":"500 m"}]'::jsonb,
    'Exclusively listed — Not available anywhere else',
    true
  ),
(
    'corp-001',
    'corporate',
    'Embassy Lake Terraces',
    'Hebbal',
    'Bengaluru',
    120000,
    600000,
    3500,
    4,
    4,
    'Fully-Furnished',
    ARRAY['/images/placeholder-corp-1.jpg','/images/placeholder-corp-2.jpg','/images/placeholder-corp-3.jpg'],
    ARRAY['Private Elevator','Helipad','Business Centre','Spa & Sauna','Chef on Call'],
    '[{"name":"Airport","distance":"25 min"},{"name":"Central Business District","distance":"20 min"},{"name":"Kirloskar Tech Park","distance":"5 min"}]'::jsonb,
    'Exclusively listed — Not available anywhere else',
    true
  ),
(
    'corp-002',
    'corporate',
    'Karle Zenith',
    'Hebbal',
    'Bengaluru',
    95000,
    450000,
    2800,
    3,
    3,
    'Fully-Furnished',
    ARRAY['/images/placeholder-corp-4.jpg','/images/placeholder-corp-5.jpg','/images/placeholder-corp-6.jpg'],
    ARRAY['Meeting Rooms','Concierge','Premium Lounge','Gym','Sky Garden'],
    '[{"name":"Karle Town Centre","distance":"Walkable"},{"name":"Manyata Tech Park","distance":"2 km"},{"name":"Taj Hotel","distance":"4 km"}]'::jsonb,
    'Exclusively listed — Not available anywhere else',
    true
  ),
(
    'corp-003',
    'corporate',
    'Bhartiya City Nikoo',
    'Yelahanka',
    'Bengaluru',
    75000,
    350000,
    2200,
    3,
    3,
    'Fully-Furnished',
    ARRAY['/images/placeholder-corp-7.jpg','/images/placeholder-corp-8.jpg','/images/placeholder-corp-9.jpg'],
    ARRAY['High-speed Internet','Work Pods','Housekeeping','Cafe','Gym'],
    '[{"name":"Bhartiya City IT Park","distance":"Within Campus"},{"name":"Manipal Hospital","distance":"2 km"},{"name":"Leela Hotel","distance":"Within Campus"}]'::jsonb,
    'Exclusively listed — Not available anywhere else',
    true
  ),
(
    'corp-004',
    'corporate',
    'Sanjeevini Vantage',
    'Hebbal',
    'Bengaluru',
    85000,
    400000,
    2500,
    3,
    3,
    'Fully-Furnished',
    ARRAY['/images/placeholder-corp-10.jpg','/images/placeholder-corp-1.jpg','/images/placeholder-corp-2.jpg'],
    ARRAY['Private Terrace','Business Lounge','Serviced Cleaning','Security','Pool'],
    '[{"name":"Kirloskar Tech Park","distance":"1 km"},{"name":"Esteem Mall","distance":"1.5 km"},{"name":"Airport Road","distance":"500 m"}]'::jsonb,
    'Exclusively listed — Not available anywhere else',
    true
  ),
(
    'corp-005',
    'corporate',
    'Prestige Augusta',
    'Yelahanka',
    'Bengaluru',
    150000,
    800000,
    4000,
    4,
    4,
    'Fully-Furnished',
    ARRAY['/images/placeholder-corp-3.jpg','/images/placeholder-corp-4.jpg','/images/placeholder-corp-5.jpg'],
    ARRAY['Golf Course Access','Private Garden','Servant Quarters','Luxury Spa','Clubhouse'],
    '[{"name":"Airport","distance":"20 min"},{"name":"Canadian Intl School","distance":"5 min"},{"name":"RMZ Galleria Mall","distance":"10 min"}]'::jsonb,
    'Exclusively listed — Not available anywhere else',
    true
  )
ON CONFLICT (id) DO UPDATE SET
  type = EXCLUDED.type,
  title = EXCLUDED.title,
  location = EXCLUDED.location,
  city = EXCLUDED.city,
  rent = EXCLUDED.rent,
  deposit = EXCLUDED.deposit,
  sqft = EXCLUDED.sqft,
  bedrooms = EXCLUDED.bedrooms,
  bathrooms = EXCLUDED.bathrooms,
  furnishing = EXCLUDED.furnishing,
  images = EXCLUDED.images,
  amenities = EXCLUDED.amenities,
  nearby_places = EXCLUDED.nearby_places,
  fomo_text = EXCLUDED.fomo_text,
  available = EXCLUDED.available;